# Es wird eine docker-compose.properties Datei im gleichen Verzeichnis vorausgesetzt wie von ierp.yml.
version: "2"

# Define custom networks
networks:
  frontend:
    driver: overlay
    driver_opts:
      foo: "bar"
      baz: 1
    labels:
      - "com.pipapo=pipapo"
      - "com.pipapo.pa=pipapo pa"
  service:
    driver: overlay
    enable_ipv6: true
  backend:
    driver: bridge
  attachment:
    external: true
    labels:
      com.pipapo: "pipapo"
      com.pipapo.pa: "pipapo pa"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  database:
    image: ${docker.pull.registry}/${docker.repository}/database:${erp.version}
    volumes:
      - ${VOLUMES_ROOT}/database/data:/data
      - ${VOLUMES_ROOT}/database/logs:/logs
    networks:
      - backend
      
  service:  
    networks:
      frontend:
        aliases:
          - alias1
          - alias2
        ipv4_address: 127.0.0.1
        ipv6_address: 2001:3984:3989::10
        link_local_ips:
          - 127.0.1.1
          - 127.0.1.2
