# Es wird eine docker-compose.properties Datei im gleichen Verzeichnis vorausgesetzt wie von ierp.yml.
version: "2"

# Define custom networks
networks:
  frontend:
    driver: overlay
    driver_opts:
      foo: "bar"
      baz: 1
  service:
    driver: overlay
  backend:
    external: true
  attachment:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  database:
    volumes:
      - ${VOLUMES_ROOT}/database/data:/data
      - ${VOLUMES_ROOT}/database/logs:/logs
    networks:
      - backend
      
  service:  
    networks:
      backend:
        aliases:
          - alias1
          - alias2
        ipv4_address: 127.0.0.1
        ipv6_address: 2001:3984:3989::10
